kind: pipeline
name: default

steps:
  - name: build_frontend
    image: docker:latest
    depends_on: [ clone ]
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build --no-cache -t geen-frontend:1.0.0.$$DRONE_BUILD_NUMBER -f "build/Frontend.Dockerfile" .

  - name: build_web
    image: docker:latest
    depends_on: [ build_frontend ]
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build  --no-cache -t geen:1.0.0.$$DRONE_BUILD_NUMBER -f "build/Web.Dockerfile" --build-arg BUILD_NUMBER=1.0.0.$$DRONE_BUILD_NUMBER .

  - name: clear
    image: docker:dind
    depends_on: [ build_web ]
    privileged: true
    failure: ignore
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker stop geen || true
      - docker rm geen || true

  - name: deploy
    image: docker:dind
    depends_on: [ clear ]
    privileged: true
    failure: ignore
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker run -d -p 172.17.0.1:7000:7000 --volume /home/zoxexivo/static/htmls:/html/geen --restart always --name geen geen:1.0.0.$$DRONE_BUILD_NUMBER

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock